# Generated by Django 4.1.7 on 2023-03-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DateTimeField(auto_now_add=True, verbose_name='Нажатие')),
            ],
            options={
                'verbose_name': 'Нажатие',
                'verbose_name_plural': 'Нажатие',
            },
        ),
    ]
