# Generated by Django 4.1.7 on 2023-03-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0002_rename_count_countmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='countmodel',
            name='team',
            field=models.CharField(default=1, max_length=255, verbose_name='Тема'),
            preserve_default=False,
        ),
    ]
